export const users = [
    { id: 1, username: 'admin', password: 'admin123', role: 'admin' },
    { id: 2, username: 'student1', password: 'pass123', role: 'student' },
    { id: 3, username: 'student2', password: 'pass456', role: 'student' },
    { id: 4, username: 'teacher1', password: 'teach789', role: 'teacher' },
    { id: 5, username: 'guest', password: 'guest000', role: 'guest' },
];

export const quizzes = [
    {
        id: 1,
        title: 'HTML & CSS Cơ Bản',
        duration: 30,
        difficulty: 'Junior',
        category: 'Thiết Kế Web',
        questions: Array.from({ length: 20 }, (_, index) => ({
            id: index + 1,
            text: 'Thẻ HTML nào dùng để tạo tiêu đề cấp 1?',
            options: ['<h1>', '<header>', '<title>', '<h6>'],
            correctAnswer: '<h1>',
        })),
    },
    {
        id: 2,
        title: 'JavaScript Nâng Cao',
        duration: 60,
        difficulty: 'Senior',
        category: 'Thiết Kế Web',
        questions: Array.from({ length: 25 }, (_, index) => ({
            id: index + 1,
            text: 'Phương thức nào thêm phần tử vào cuối mảng trong JavaScript?',
            options: ['push()', 'pop()', 'shift()', 'unshift()'],
            correctAnswer: 'push()',
        })),
    },
    {
        id: 3,
        title: 'React Framework',
        duration: 45,
        difficulty: 'Mid-level',
        category: 'Thiết Kế Web',
        questions: Array.from({ length: 22 }, (_, index) => ({
            id: index + 1,
            text: 'Hook nào dùng để quản lý trạng thái trong React?',
            options: ['useState', 'useEffect', 'useRef', 'useContext'],
            correctAnswer: 'useState',
        })),
    },
    {
        id: 4,
        title: 'Android Cơ Bản',
        duration: 40,
        difficulty: 'Junior',
        category: 'Mobile',
        questions: Array.from({ length: 23 }, (_, index) => ({
            id: index + 1,
            text: 'Thành phần nào là giao diện chính trong Android?',
            options: ['Activity', 'Service', 'Broadcast', 'Content Provider'],
            correctAnswer: 'Activity',
        })),
    },
    {
        id: 5,
        title: 'iOS với Swift',
        duration: 50,
        difficulty: 'Mid-level',
        category: 'Mobile',
        questions: Array.from({ length: 27 }, (_, index) => ({
            id: index + 1,
            text: 'Cú pháp nào khai báo biến hằng trong Swift?',
            options: ['let', 'var', 'const', 'static'],
            correctAnswer: 'let',
        })),
    },
    {
        id: 6,
        title: 'Flutter Development',
        duration: 60,
        difficulty: 'Senior',
        category: 'Mobile',
        questions: Array.from({ length: 26 }, (_, index) => ({
            id: index + 1,
            text: 'Widget nào cung cấp cấu trúc cơ bản cho ứng dụng Flutter?',
            options: ['Scaffold', 'Container', 'Text', 'Row'],
            correctAnswer: 'Scaffold',
        })),
    },
    {
        id: 7,
        title: 'CCNA Cơ Bản',
        duration: 60,
        difficulty: 'Junior',
        category: 'Mạng Máy Tính',
        questions: Array.from({ length: 20 }, (_, index) => ({
            id: index + 1,
            text: 'Giao thức nào dùng để định tuyến trong mạng?',
            options: ['OSPF', 'HTTP', 'FTP', 'DNS'],
            correctAnswer: 'OSPF',
        })),
    },
    {
        id: 8,
        title: 'Bảo Mật Mạng',
        duration: 75,
        difficulty: 'Senior',
        category: 'Mạng Máy Tính',
        questions: Array.from({ length: 28 }, (_, index) => ({
            id: index + 1,
            text: 'Tấn công DDoS nhắm vào tầng nào của mô hình OSI?',
            options: ['Application', 'Network', 'Transport', 'All layers'],
            correctAnswer: 'All layers',
        })),
    },
    {
        id: 9,
        title: 'Quản Trị Hệ Thống',
        duration: 50,
        difficulty: 'Mid-level',
        category: 'Mạng Máy Tính',
        questions: Array.from({ length: 24 }, (_, index) => ({
            id: index + 1,
            text: 'Lệnh nào kiểm tra trạng thái dịch vụ trong Linux?',
            options: ['systemctl', 'service', 'ps', 'top'],
            correctAnswer: 'systemctl',
        })),
    },
];